[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200